services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pdf_reader
      POSTGRES_PASSWORD: pdf_reader
      POSTGRES_DB: pdf_reader
    ports:
      - '5432:5432'
    volumes:
      - pdf_reader_pg_data:/var/lib/postgresql/data

volumes:
  pdf_reader_pg_data:
